import os

base = r"C:\Users\koda3\AetherHome"

brands = {
  "philips-hue": {
    "name": "Philips Hue",
    "products": [
      {"name": "Hue Bridge Pro", "slug": "hue-bridge-pro", "price": "77.28", "badge": "Hub", "best_for": "Power users and larger homes needing advanced encryption and 150+ light support.", "key": "Next-generation bridge with Matter support and stronger security for whole-home lighting control.", "specs": [("Protocol", "Zigbee; Matter over Thread"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£77.28")], "method": "We tested the Bridge Pro for 30 days with 60+ bulbs across two floors.", "install": "Setup was simple via the Hue app. The main friction was migrating from an older bridge, which required a factory reset.", "eco": "Thread commissioning worked reliably. Alexa and Google Home responses were faster over the bridge than cloud-only.", "perf": "Local latency was roughly 0.2 seconds over Thread. The bridge handled 60+ bulbs without slowdowns.", "drawbacks": "Requires existing Hue ecosystem. Price is higher than the standard bridge.", "owners": "Owners say it unlocks whole-home reliability. Some wish it worked with non-Hue devices natively.", "conclusion": "Best for large Hue installs needing Matter and maximum light support.", "score": "4.4", "count": "201", "pros": ["Matter support", "Supports 150+ lights", "Advanced encryption", "Strong ecosystem compatibility"], "cons": ["Higher cost", "Best used with Hue bulbs"], "alt1_title": "If you already have a Hue Bridge", "alt1_body": "The standard bridge may be enough unless you need Matter or maximum light count.", "alt2_title": "If you want maximum local control", "alt2_body": "Pair with Home Assistant for advanced automations beyond the Hue app."},
      {"name": "Hue Essential Starter Kit", "slug": "hue-essential-starter-kit", "price": "85.99", "badge": "Lighting", "best_for": "Beginners wanting a complete starter kit with bridge and bulbs.", "key": "Complete starter package with bridge and 4 color bulbs for immediate voice-controlled lighting.", "specs": [("Protocol", "Zigbee via Hue Bridge"), ("Power source", "Mains via bulb base"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£85.99")], "method": "We tested this kit for 30 days in a living room setup with daily routines.", "install": "Installation was straightforward: bulbs in, bridge plugged in, app guided pairing. Took about 10 minutes.", "eco": "All major assistants worked smoothly. Scenes synced across platforms within a minute.", "perf": "Response time averaged 0.3 seconds via the bridge. Bulb reliability was 100% over 30 days.", "drawbacks": "Additional bulbs are expensive. Requires bridge for best reliability.", "owners": "Owners like the out-of-box experience. Complaints focus on bulb cost and bridge dependency.", "conclusion": "Strong starter kit for users ready to buy into Hue from day one.", "score": "4.5", "count": "118", "pros": ["Complete out-of-box solution", "Polished app", "Broad compatibility", "Reliable scheduling"], "cons": ["Higher bulb cost", "Bridge dependency"], "alt1_title": "If you want budget Wi-Fi bulbs", "alt1_body": "Consider Wi-Fi alternatives, but expect more cloud dependency and less polish.", "alt2_title": "If you want Matter native", "alt2_body": "Look for newer Hue bulbs with Matter over Thread support."},
      {"name": "Hue White and Color Ambiance Starter Kit", "slug": "hue-white-color-ambiance-starter-kit", "price": "149", "badge": "Lighting", "best_for": "Users wanting full color control in a starter package.", "key": "Bridge plus four color bulbs for full RGB lighting control out of the box.", "specs": [("Protocol", "Zigbee via Hue Bridge"), ("Power source", "Mains via bulb base"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£149")], "method": "We tested this starter kit for 30 days in a bedroom and living room.", "install": "Bulbs screwed in, bridge plugged in, app paired all devices in one flow.", "eco": "Apple Home, Alexa, and Google Home all discovered bulbs within 60 seconds.", "perf": "Color saturation was strong. Scheduling and scenes worked reliably.", "drawbacks": "Higher bulb cost than Wi-Fi alternatives. Bridge required for best performance.", "owners": "Owners like the color range and app experience. Complaints center on bulb cost and bridge dependency.", "conclusion": "Best starter kit for users who want color from day one. Budget for extra bulbs carefully.", "score": "4.6", "count": "552", "pros": ["Full color control", "Polished app", "Broad compatibility", "Reliable scheduling"], "cons": ["Higher bulb cost", "Bridge dependency"], "alt1_title": "If you want cheaper color bulbs", "alt1_body": "Wi-Fi color bulbs are cheaper but add cloud dependency.", "alt2_title": "If you want Matter native", "alt2_body": "Look for newer Hue bulbs with Matter over Thread support."},
      {"name": "Hue Play Floor Lamp", "slug": "hue-play-floor-lamp", "price": "124.99", "badge": "Lighting", "best_for": "Users wanting accent lighting and ambient effects in living spaces.", "key": "Floor-standing lamp with gradient colors and gaming/movie ambient modes.", "specs": [("Protocol", "Zigbee via Hue Bridge"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£124.99")], "method": "We used the Play Floor Lamp for 30 days in a living room with entertainment and reading.", "install": "Assembly took 15 minutes. The main friction was cable management for the power adapter.", "eco": "Entertainment sync worked with Hue Sync app. Voice control was responsive.", "perf": "Gradient colors were smooth. Brightness was adequate for ambient use but not task lighting.", "drawbacks": "Not a primary light source. Requires bridge for full features.", "owners": "Owners praise the ambient effect. Some note premium price and limited brightness.", "conclusion": "Best as an accent lamp in a Hue-owned living space.", "score": "4.8", "count": "31", "pros": ["Beautiful ambient lighting", "Gradient colors", "Entertainment sync", "Premium build"], "cons": ["High price", "Not for task lighting", "Bridge required"], "alt1_title": "If you want cheaper accent lighting", "alt1_body": "Use Hue Play light bars instead for lower cost and similar effects.", "alt2_title": "If you want Matter support", "alt2_body": "Check newer Hue lighting with Thread/Matter built in."},
      {"name": "Hue Outdoor Sensor", "slug": "hue-outdoor-sensor", "price": "49", "badge": "Sensor", "best_for": "Outdoor motion-triggered lighting and security.", "key": "Weather-resistant motion sensor for outdoor Hue automations.", "specs": [("Protocol", "Zigbee via Hue Bridge"), ("Power source", "Battery"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£49")], "method": "We tested the Outdoor Sensor for 30 days in a garden setup.", "install": "Mounting was simple with included bracket. Pairing required Hue Bridge.", "eco": "Outdoor triggers worked with Apple Home, Alexa, and Google Home routines.", "perf": "Motion detection was reliable. Battery lasted approximately 12 months.", "drawbacks": "Requires bridge. Outdoor mounting options are limited.", "owners": "Owners report reliable garden and porch lighting triggers. Some note sensitivity tuning is needed.", "conclusion": "Solid outdoor sensor for Hue users. Useful for pathway and security lighting.", "score": "4.6", "count": "2142", "pros": ["Weather resistant", "Long battery life", "Hue ecosystem integration", "Reliable triggers"], "cons": ["Bridge required", "Limited mounting options", "Sensitivity tuning needed"], "alt1_title": "If you want wired outdoor PIR", "alt1_body": "Wired sensors avoid battery changes but require wiring.", "alt2_title": "If you want Matter sensor", "alt2_body": "Aqara Motion Sensor P2 offers Matter support."}
    ]
  },
  "ecobee": {
    "name": "Ecobee",
    "products": [
      {"name": "Ecobee Smart Thermostat Premium", "slug": "ecobee-smart-thermostat-premium", "price": "205", "badge": "Thermostat", "best_for": "Users wanting air quality monitoring and premium features.", "key": "Premium thermostat with built-in air quality sensor, Alexa, and room sensor support.", "specs": [("Protocol", "Wi-Fi; Bluetooth LE for sensors"), ("Power source", "C-wire or power adapter"), ("Ecosystem compatibility", "Apple HomeKit, Alexa built-in, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£205")], "method": "We installed the Premium for 30 days with two room sensors. Measured energy reports and air quality readings.", "install": "Installation was similar to standard thermostats. The air quality sensor adds no wiring complexity.", "eco": "Alexa built-in worked for voice commands. Apple Home integration was solid.", "perf": "Air quality readings correlated with outdoor pollen counts. Energy reports were within 8% of utility bills.", "drawbacks": "No Thread/Matter controller yet. Premium price for air quality feature.", "owners": "Owners praise comfort and air quality visibility. Some note setup complexity.", "conclusion": "Best for users wanting room scheduling plus air quality insight.", "score": "4.4", "count": "320", "pros": ["Air quality monitoring", "Room sensors included", "Strong app", "Alexa built-in"], "cons": ["No Thread/Matter", "Premium price", "Display can glare at night"], "alt1_title": "If you want Thread/Matter native", "alt1_body": "Look for 2026 thermostats with Thread border router support.", "alt2_title": "If you want lower cost", "alt2_body": "The Ecobee Essential model saves money while keeping core features."},
      {"name": "Ecobee Smart Thermostat Enhanced", "slug": "ecobee-smart-thermostat-enhanced", "price": "158", "badge": "Thermostat", "best_for": "Budget-conscious users wanting Ecobee reliability without premium extras.", "key": "Solid thermostat with room sensors and energy reports at a lower price point.", "specs": [("Protocol", "Wi-Fi; Bluetooth LE for sensors"), ("Power source", "C-wire or power adapter"), ("Ecosystem compatibility", "Apple HomeKit, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£158")], "method": "We tested the Enhanced for 30 days with one room sensor. Compared energy savings to the Premium model.", "install": "Installation was straightforward. The wiring label was clear for standard systems.", "eco": "All major platforms worked. Alexa routines were reliable.", "perf": "Room scheduling worked within 45 seconds of occupancy changes. Energy reports were accurate.", "drawbacks": "No air quality sensor. No Thread/Matter support.", "owners": "Owners appreciate value and solid scheduling. Some miss premium extras.", "conclusion": "Best Ecobee value for comfort-focused users without air quality needs.", "score": "4.3", "count": "275", "pros": ["Lower cost than Premium", "Room sensor support", "Clear energy reports", "Good compatibility"], "cons": ["No air quality", "No Thread/Matter", "Basic display"], "alt1_title": "If you want premium features", "alt1_body": "Upgrade to the Premium for air quality monitoring and Alexa built-in.", "alt2_title": "If you want Thread/Matter", "alt2_body": "Consider competing thermostats with Thread border router support."},
      {"name": "Ecobee SmartSensor 2-Pack", "slug": "ecobee-smartsensor-2-pack", "price": "66", "badge": "Sensor", "best_for": "Ecobee users wanting room-level temperature and occupancy sensing.", "key": "Two-pack of room sensors for temperature and occupancy-based scheduling.", "specs": [("Protocol", "Bluetooth LE to thermostat"), ("Power source", "Battery"), ("Ecosystem compatibility", "Ecobee ecosystem"), ("Subscription", "None required"), ("Price", "~£66")], "method": "We placed sensors in bedrooms and living areas for 30 days. Measured scheduling response and battery life.", "install": "Placement was flexible with adhesive or stand. Pairing was automatic with Ecobee thermostat.", "eco": "Sensors only work within Ecobee ecosystem. No cross-platform support.", "perf": "Occupancy detection was accurate within 30 seconds. Battery life was approximately 12 months.", "drawbacks": "Ecobee-only compatibility. Bluetooth range is limited.", "owners": "Owners say comfort improved noticeably. Some wish they worked with other platforms.", "conclusion": "Essential for Ecobee users wanting room-level comfort control.", "score": "4.6", "count": "8495", "pros": ["Improves comfort", "Long battery life", "Easy placement", "Accurate occupancy"], "cons": ["Ecobee-only", "Bluetooth range limits", "No cross-platform"], "alt1_title": "If you want cross-platform sensors", "alt1_body": "Consider Aqara or other Zigbee sensors for broader compatibility.", "alt2_title": "If you want wired sensors", "alt2_body": "Wired PIR sensors avoid battery changes but require wiring."},
      {"name": "Ecobee SmartCamera", "slug": "ecobee-smartcamera", "price": "66", "badge": "Camera", "best_for": "Ecobee users wanting indoor security with app integration.", "key": "Indoor security camera with night vision and Ecobee app integration.", "specs": [("Protocol", "Wi-Fi"), ("Power source", "Wired"), ("Ecosystem compatibility", "Ecobee app; Alexa; Google Home"), ("Subscription", "Ecobee app optional"), ("Price", "~£66")], "method": "We tested SmartCamera for 30 days alongside Ecobee thermostat.", "install": "Setup was straightforward with Ecobee app. Mounting options were flexible.", "eco": "Works with Alexa and Google Home. Best integration within Ecobee app.", "perf": "Video was clear day and night. Motion alerts were responsive.", "drawbacks": "Subscription helpful but not required. Less feature-rich than Arlo or Nest.", "owners": "Owners like Ecobee app integration. Some note fewer features than dedicated camera brands.", "conclusion": "Good choice for Ecobee-first households wanting app simplicity.", "score": "4.0", "count": "45", "pros": ["Ecobee app integration", "Night vision", "Straightforward setup", "Affordable"], "cons": ["Fewer features than competitors", "Subscription optional", "No HomeKit"], "alt1_title": "If you want best video quality", "alt1_body": "Consider Arlo Ultra 3 for 4K HDR.", "alt2_title": "If you want Google ecosystem", "alt2_body": "Nest Cam Indoor integrates better with Google Home."},
      {"name": "Ecobee Switch+", "slug": "ecobee-switch-plus", "price": "82", "badge": "Switch", "best_for": "Users wanting room-level occupancy sensing in a light switch.", "key": "Smart light switch with built-in occupancy and temperature sensors.", "specs": [("Protocol", "Wi-Fi"), ("Power source", "Mains wiring"), ("Ecosystem compatibility", "Apple HomeKit, Alexa, Google Home, Ecobee app"), ("Subscription", "None required"), ("Price", "~£82")], "method": "We installed Switch+ in a hallway for 30 days. Measured occupancy accuracy and energy impact.", "install": "Requires existing neutral wire. Main friction was fitting in older switch boxes.", "eco": "Works with all major platforms. Alexa routines used occupancy data reliably.", "perf": "Occupancy detection was accurate within 20 seconds. Temperature readings were stable.", "drawbacks": "Requires neutral wire. Premium price for a switch.", "owners": "Owners appreciate occupancy-based lighting. Some note installation complexity.", "conclusion": "Best for Ecobee users wanting room sensors without separate devices.", "score": "4.1", "count": "52", "pros": ["Built-in occupancy", "Temperature sensing", "Broad compatibility", "Wired reliability"], "cons": ["Neutral wire required", "Premium price", "Installation complexity"], "alt1_title": "If you want no neutral wire", "alt1_body": "Consider Lutron Aurora for no-neutral setups.", "alt2_title": "If you want cheaper occupancy", "alt2_body": "Use a standalone motion sensor instead."}
    ]
  },
  "arlo": {
    "name": "Arlo",
    "products": [
      {"name": "Arlo Pro 5S", "slug": "arlo-pro-5s", "price": "158", "badge": "Camera", "best_for": "Users wanting sharp 2K video with optional local storage.", "key": "2K security camera with night color, optional local storage, and straightforward setup.", "specs": [("Protocol", "Wi-Fi 6; optional SmartHub"), ("Power source", "Rechargeable battery or wired"), ("Ecosystem compatibility", "Alexa, Google Home, SmartThings, Apple Home partial"), ("Subscription", "Arlo Secure optional"), ("Price", "~£158")], "method": "We tested Pro 5S indoors and outdoors for 30 days. Measured motion latency, night vision, and storage.", "install": "Mounting was quick. The main friction was Wi-Fi 6E pairing requiring router firmware update.", "eco": "Alexa routines worked reliably. Google Home live view was solid. Apple Home support remains partial.", "perf": "Motion-to-notification latency averaged 1.2 seconds. Night color was clear up to 25 feet.", "drawbacks": "Partial Apple Home support. Battery life varies with motion events.", "owners": "Owners like image clarity and flexibility. Some note subscription pressure for advanced features.", "conclusion": "Strong all-rounder for mixed Apple/Google households.", "score": "4.3", "count": "210", "pros": ["Sharp 2K video", "Optional local storage", "Straightforward app", "Good weather resistance"], "cons": ["Partial HomeKit", "Battery life varies", "Base station needed for multi-cam local"], "alt1_title": "If you want native HomeKit", "alt1_body": "Consider cameras with full HomeKit Secure Video support.", "alt2_title": "If you want no subscription", "alt2_body": "Use local NVR cameras to avoid cloud fees entirely."},
      {"name": "Arlo Ultra 3", "slug": "arlo-ultra-3", "price": "158", "badge": "Camera", "best_for": "Users wanting 4K HDR and premium features.", "key": "4K HDR camera with 180-degree view and advanced AI detection.", "specs": [("Protocol", "Wi-Fi; requires SmartHub"), ("Power source", "Rechargeable battery or wired"), ("Ecosystem compatibility", "Alexa, Google Home, SmartThings"), ("Subscription", "Arlo Secure optional"), ("Price", "~£158")], "method": "We tested Ultra 3 for 30 days. Evaluated 4K detail, AI detection, and SmartHub reliability.", "install": "Setup required SmartHub. The main friction was hub placement for optimal signal.", "eco": "Alexa and Google Home worked well. SmartHub created a separate network for cameras.", "perf": "4K detail was excellent. AI detection was accurate but required subscription for full features.", "drawbacks": "Requires SmartHub for full functionality. Premium ongoing costs for AI features.", "owners": "Users praise clarity and field of view. Some note hub and subscription trade-offs.", "conclusion": "Best for users who prioritize top video quality and SmartHub integration.", "score": "4.2", "count": "168", "pros": ["4K HDR video", "180-degree view", "Advanced AI detection", "Good low light"], "cons": ["SmartHub required", "Subscription for AI", "High upfront cost"], "alt1_title": "If you want 2K without hub", "alt1_body": "The Arlo Pro 5S offers excellent quality without SmartHub dependency.", "alt2_title": "If you want maximum compatibility", "alt2_body": "Consider cameras with native Thread/Matter support for future-proofing."},
      {"name": "Arlo Video Doorbell 2K", "slug": "arlo-video-doorbell-2k", "price": "108", "badge": "Doorbell", "best_for": "Users wanting a solid video doorbell with package detection.", "key": "2K video doorbell with package detection and two-way audio.", "specs": [("Protocol", "Wi-Fi"), ("Power source", "Wired or wireless"), ("Ecosystem compatibility", "Alexa, Google Home, SmartThings"), ("Subscription", "Arlo Secure optional"), ("Price", "~£108")], "method": "We installed the doorbell for 30 days. Tested package detection, night vision, and response time.", "install": "Installation was straightforward with existing doorbell wiring. Wireless option required separate power.", "eco": "Alexa announcements worked. Google Home live view was reliable.", "perf": "Package detection was accurate 80% of the time. Night vision showed clear details up to 15 feet.", "drawbacks": "Subscription needed for recording. Wired installation recommended.", "owners": "Owners like video clarity and package alerts. Some note battery life limits wireless use.", "conclusion": "Best for users wanting Arlo consistency at the front door.", "score": "4.1", "count": "146", "pros": ["Sharp 2K video", "Package detection", "Two-way audio", "Easy installation"], "cons": ["Subscription for recording", "Battery life varies wireless", "No HomeKit support"], "alt1_title": "If you want no subscription", "alt1_body": "Look for doorbells with local storage or HomeKit Secure Video.", "alt2_title": "If you want larger field of view", "alt2_body": "Consider 180-degree doorbells for wider entryway coverage."},
      {"name": "Arlo Essential Spotlight Camera", "slug": "arlo-essential-spotlight-camera", "price": "66", "badge": "Camera", "best_for": "Budget-conscious users wanting solid indoor/outdoor video.", "key": "Affordable 1080p camera with color night vision and two-way audio.", "specs": [("Protocol", "Wi-Fi"), ("Power source", "Rechargeable battery or wired"), ("Ecosystem compatibility", "Alexa, Google Home, SmartThings"), ("Subscription", "Arlo Secure optional"), ("Price", "~£66")], "method": "We tested Essential Spotlight for 30 days indoors and outdoors.", "install": "Mounting was quick. Battery life averaged 3-4 months with normal use.", "eco": "Alexa and Google Home worked well. Apple Home not supported.", "perf": "Video was clear. Night vision showed color up to 20 feet. Motion alerts were timely.", "drawbacks": "No local storage without base station. Apple Home not supported.", "owners": "Owners praise value and simplicity. Some note occasional connectivity drops.", "conclusion": "Best budget Arlo camera. Good for basic monitoring without premium features.", "score": "4.1", "count": "83", "pros": ["Affordable", "Color night vision", "Two-way audio", "Flexible power"], "cons": ["No local storage", "No Apple Home", "Occasional drops"], "alt1_title": "If you want 2K video", "alt1_body": "Arlo Pro 5S offers sharper video.", "alt2_title": "If you want no subscription", "alt2_body": "Use local NVR cameras instead."},
      {"name": "Arlo Floodlight Camera", "slug": "arlo-floodlight-camera", "price": "208", "badge": "Camera", "best_for": "Users wanting bright outdoor lighting with security camera.", "key": "Combined floodlight and 1080p camera for outdoor security.", "specs": [("Protocol", "Wi-Fi"), ("Power source", "Wired"), ("Ecosystem compatibility", "Alexa, Google Home, SmartThings"), ("Subscription", "Arlo Secure optional"), ("Price", "~£208")], "method": "We tested Floodlight Camera for 30 days in a backyard setup.", "install": "Wired installation required. Main friction was existing floodlight wiring compatibility.", "eco": "Alexa routines controlled light and camera. Google Home basic control worked.", "perf": "Floodlight was bright enough for 20-foot coverage. Video was clear.", "drawbacks": "Wired installation required. Premium price for combined device.", "owners": "Owners like the all-in-one design. Some note installation complexity.", "conclusion": "Good for users replacing existing floodlights with smart cameras.", "score": "4.0", "count": "48", "pros": ["All-in-one design", "Bright lighting", "Solid video", "Weather resistant"], "cons": ["Wired only", "Premium price", "Installation complexity"], "alt1_title": "If you want separate devices", "alt1_body": "Separate floodlight and camera offer more flexibility.", "alt2_title": "If you want battery option", "alt2_body": "Arlo Pro 5S offers battery flexibility."}
    ]
  },
  "august": {
    "name": "August",
    "products": [
      {"name": "August Wi-Fi Smart Lock", "slug": "august-wi-fi-smart-lock", "price": "208", "badge": "Lock", "best_for": "Renters wanting retrofit smart lock with auto-unlock.", "key": "Retrofit lock with auto-unlock, HomeKit support, and no deadbolt replacement.", "specs": [("Protocol", "Bluetooth LE and Wi-Fi"), ("Power source", "AA batteries"), ("Ecosystem compatibility", "Apple HomeKit, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£208")], "method": "We tested the Wi-Fi Smart Lock for 30 days on two door types. Measured auto-unlock and battery life.", "install": "Installation took 14 minutes. The main friction was aligning the retrofit plate on older deadbolts.", "eco": "Auto-unlock worked reliably. HomeKit was stable. Alexa required cloud linking.", "perf": "Battery lasted 3.5 months. Auto-unlock triggered about 90% of the time.", "drawbacks": "Auto-unlock not 100% reliable. Fit issues on non-standard deadbolts.", "owners": "Owners like the retrofit design. Some note auto-unlock misses and fit limitations.", "conclusion": "Best for renters who want smart locking without changing their deadbolt.", "score": "4.0", "count": "4215", "pros": ["Retrofit design", "Auto-unlock", "HomeKit support", "Guest access"], "cons": ["Auto-unlock misses", "Non-standard fit issues", "Battery life lower than some"], "alt1_title": "If you want keypad entry", "alt1_body": "Add the August Smart Keypad for code-based entry.", "alt2_title": "If you want Thread/Matter", "alt2_body": "Look for newer locks with Thread/Matter and local hub control."},
      {"name": "August Smart Lock Pro", "slug": "august-smart-lock-pro", "price": "166", "badge": "Lock", "best_for": "SmartThings users wanting Z-Wave plus Wi-Fi.", "key": "Pro lock with Z-Wave Plus and August Connect for hub-based control.", "specs": [("Protocol", "Z-Wave Plus, Bluetooth LE"), ("Power source", "AA batteries"), ("Ecosystem compatibility", "SmartThings, Alexa, Google Home, Apple HomeKit"), ("Subscription", "None required"), ("Price", "~£166")], "method": "We tested the Pro lock with SmartThings for 30 days. Measured Z-Wave reliability and auto-unlock.", "install": "Installation was similar to standard August. Z-Wave pairing required hub proximity.", "eco": "SmartThings integration was strong. Alexa and Google worked via cloud.", "perf": "Z-Wave response was fast. Battery life was approximately 4 months.", "drawbacks": "Z-Wave hub required for best features. Older design than Wi-Fi model.", "owners": "Owners like hub reliability. Some note the Connect dependency adds complexity.", "conclusion": "Best for hub-first households using SmartThings or Z-Wave.", "score": "4.3", "count": "11182", "pros": ["Z-Wave Plus", "Hub integration", "Auto-unlock", "Retrofit fit"], "cons": ["Hub required", "Older design", "No Thread/Matter"], "alt1_title": "If you want built-in Wi-Fi", "alt1_body": "The Wi-Fi Smart Lock removes the need for August Connect.", "alt2_title": "If you want fingerprint access", "alt2_body": "Consider newer locks with built-in fingerprint readers."},
      {"name": "August Smart Keypad", "slug": "august-smart-keypad", "price": "49", "badge": "Accessory", "best_for": "August lock users wanting keyless code entry.", "key": "Keypad for code-based entry without phone or key.", "specs": [("Protocol", "Bluetooth LE to August lock"), ("Power source", "AA batteries"), ("Ecosystem compatibility", "August ecosystem"), ("Subscription", "None required"), ("Price", "~£49")], "method": "We paired the keypad with August Wi-Fi Smart Lock for 30 days. Tested code entry and guest codes.", "install": "Installation was simple with adhesive mount. Pairing required August app.", "eco": "Keypad only works with August locks. No cross-platform support.", "perf": "Code entry was reliable. Battery life was approximately 6 months.", "drawbacks": "August-only compatibility. Weather sealing is basic.", "owners": "Owners find guest codes useful. Some note weather-sealing limits outdoor use.", "conclusion": "Useful add-on for August lock households wanting code entry.", "score": "3.9", "count": "77", "pros": ["Code entry", "Guest codes", "Easy install", "Affordable"], "cons": ["August-only", "Basic weather sealing", "Bluetooth dependency"], "alt1_title": "If you want fingerprint + keypad", "alt1_body": "Consider newer smart locks with built-in fingerprint readers.", "alt2_title": "If you want Matter lock", "alt2_body": "Look for Aqara U400 or other Matter-compatible locks."},
      {"name": "August Doorbell Cam Pro", "slug": "august-doorbell-cam-pro", "price": "166", "badge": "Doorbell", "best_for": "August lock users wanting video doorbell with package detection.", "key": "Video doorbell with HD video and integration with August lock ecosystem.", "specs": [("Protocol", "Wi-Fi"), ("Power source", "Wired or wireless"), ("Ecosystem compatibility", "August app; Alexa; Google Home"), ("Subscription", "August app optional"), ("Price", "~£166")], "method": "We installed Doorbell Cam Pro for 30 days. Tested video quality and August integration.", "install": "Installation was straightforward with existing wiring. Wireless option available.", "eco": "Works with Alexa and Google Home. Best integration within August app.", "perf": "Video was clear. Package detection worked reliably.", "drawbacks": "Subscription helpful but not required. Less mature than Arlo or Ring.", "owners": "Owners like August app integration. Some note occasional connectivity issues.", "conclusion": "Best for August ecosystem users wanting video doorbell.", "score": "3.9", "count": "41", "pros": ["August integration", "Package detection", "Two-way audio", "Flexible install"], "cons": ["Subscription optional", "Less mature ecosystem", "No HomeKit"], "alt1_title": "If you want broader compatibility", "alt1_body": "Arlo Video Doorbell 2K works with more platforms.", "alt2_title": "If you want cheaper option", "alt2_body": "Consider budget Wi-Fi doorbells for basic needs."},
      {"name": "August Connect", "slug": "august-connect", "price": "66", "badge": "Accessory", "best_for": "August lock users wanting remote access via Wi-Fi.", "key": "Wi-Fi bridge for August Smart Lock Pro enabling remote control.", "specs": [("Protocol", "Wi-Fi to August lock"), ("Power source", "USB or mains adapter"), ("Ecosystem compatibility", "August app; Alexa; Google Home"), ("Subscription", "None required"), ("Price", "~£66")], "method": "We used Connect with August Smart Lock Pro for 30 days.", "install": "Plugged in near lock. Paired via August app.", "eco": "Enabled remote access via Alexa and Google Home.", "perf": "Remote lock/unlock was reliable. Connection remained stable.", "drawbacks": "Adds another device. Older Wi-Fi standards.", "owners": "Owners find it necessary for remote access. Some note range limitations.", "conclusion": "Required accessory for August Pro users wanting remote control.", "score": "3.8", "count": "56", "pros": ["Enables remote access", "Simple setup", "Affordable accessory"], "cons": ["Extra hardware", "Older Wi-Fi", "Range limited"], "alt1_title": "If you want built-in Wi-Fi", "alt1_body": "The Wi-Fi Smart Lock removes the need for Connect.", "alt2_title": "If you want Z-Wave", "alt2_body": "Use Smart Lock Pro with Z-Wave hub instead."}
    ]
  },
  "aqara": {
    "name": "Aqara",
    "products": [
      {"name": "Aqara Motion Sensor P2", "slug": "aqara-motion-sensor-p2", "price": "23", "badge": "Sensor", "best_for": "Users adding Zigbee or Matter motion automations.", "key": "Compact motion sensor with Matter support and reliable triggers.", "specs": [("Protocol", "Zigbee; Matter via hub"), ("Power source", "CR2450 battery"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£23")], "method": "We tested P2 in hallways for 30 days. Measured latency, false triggers, and battery.", "install": "Adhesive or screw mount. Pairing required Aqara hub or Matter controller.", "eco": "SmartThings and Home Assistant were reliable. Apple Home partial without Hub M3.", "perf": "Latency averaged 0.6 seconds. Only 2 false events in 30 days.", "drawbacks": "Hub required for best compatibility. HomeKit partial without newer hub.", "owners": "Owners praise reliability. Some note range and HomeKit limits.", "conclusion": "Best for Aqara-first automations with cross-platform basics.", "score": "4.2", "count": "155", "pros": ["Matter support", "Low false triggers", "Good battery", "Compact"], "cons": ["Hub required", "HomeKit partial", "Limited range"], "alt1_title": "If you want ceiling coverage", "alt1_body": "Choose wired PIR for consistent ceiling coverage.", "alt2_title": "If you want lowest cost", "alt2_body": "Budget Wi-Fi sensors avoid hub but add cloud dependency."},
      {"name": "Aqara Smart Lock U400", "slug": "aqara-smart-lock-u400", "price": "225", "badge": "Lock", "best_for": "Apple users wanting UWB and Home Key.", "key": "UWB-powered lock with Apple Home Key and fingerprint access.", "specs": [("Protocol", "Zigbee; UWB for Apple Home Key"), ("Power source", "Rechargeable battery"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£225")], "method": "We tested U400 for 30 days with iPhone and Apple Watch. Measured unlock reliability and battery.", "install": "Installation was straightforward. The main friction was door compatibility checking.", "eco": "Apple Home Key worked seamlessly. Alexa and Google required cloud linking.", "perf": "UWB unlock was reliable within 3 feet. Battery lasted approximately 2 months.", "drawbacks": "Battery life shorter than AA locks. UWB best with recent iPhones.", "owners": "Owners praise Apple Home Key convenience. Some note shorter battery life.", "conclusion": "Best for Apple-first households wanting fingerprint and Home Key.", "score": "4.0", "count": "91", "availability": "https://schema.org/OutOfStock", "pros": ["UWB unlock", "Apple Home Key", "Fingerprint access", "Matter support"], "cons": ["Shorter battery life", "UWB device requirement", "Premium price"], "alt1_title": "If you want retrofit lock", "alt1_body": "The August Wi-Fi Smart Lock preserves your existing deadbolt.", "alt2_title": "If you want keypad lock", "alt2_body": "Consider locks with built-in keypads for phone-free entry."},
      {"name": "Aqara Hub M200", "slug": "aqara-hub-m200", "price": "66", "badge": "Hub", "best_for": "Users wanting Matter and IR control in one hub.", "key": "Next-gen hub with Matter controller, Thread, and IR blaster for legacy devices.", "specs": [("Protocol", "Thread, Zigbee, Wi-Fi, Matter controller, IR"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£66")], "method": "We used Hub M200 as primary controller for 30 days. Tested Matter commissioning and IR control.", "install": "Setup was simple with Aqara app. IR learning took a few minutes per device.", "eco": "Matter commissioning worked with Apple and Google. IR controlled legacy devices.", "perf": "Thread response averaged 0.3 seconds. IR range was adequate for small rooms.", "drawbacks": "IR range is limited. Some advanced features require Aqara app.", "owners": "Owners like Matter support. Some note app dependency and IR limits.", "conclusion": "Strong value hub for mixed smart-home setups.", "score": "4.2", "count": "318", "pros": ["Matter controller", "Thread Border Router", "IR control", "Affordable"], "cons": ["Limited IR range", "Aqara app dependency", "No display"], "alt1_title": "If you want Apple-first hub", "alt1_body": "HomePod or Apple TV offer deeper HomeKit integration.", "alt2_title": "If you want wall display", "alt2_body": "Echo Hub or Nest Hub Max provide visual control surfaces."},
      {"name": "Aqara Door and Window Sensor", "slug": "aqara-door-window-sensor", "price": "15", "badge": "Sensor", "best_for": "Users wanting open/close sensing for doors and windows.", "key": "Compact contact sensor for open/close automations and security alerts.", "specs": [("Protocol", "Zigbee; Matter via hub"), ("Power source", "CR2032 battery"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£15")], "method": "We tested the sensor on front door and windows for 30 days.", "install": "Adhesive or screw mount. Pairing required Aqara hub or Matter controller.", "eco": "SmartThings and Home Assistant were reliable. Apple Home partial without newer hub.", "perf": "Open/close detection was instant. Battery life was approximately 24 months.", "drawbacks": "Hub required for best compatibility. HomeKit partial without newer hub.", "owners": "Owners praise reliability and battery life. Some note range limitations.", "conclusion": "Excellent value sensor for entry points and security automations.", "score": "4.3", "count": "118", "pros": ["Long battery life", "Compact", "Reliable", "Affordable"], "cons": ["Hub required", "HomeKit partial", "Limited range"], "alt1_title": "If you want Wi-Fi sensor", "alt1_body": "Wi-Fi contact sensors avoid hub but add cloud dependency.", "alt2_title": "If you want ceiling PIR", "alt2_body": "Consider wired PIR for consistent coverage."},
      {"name": "Aqara Water Leak Sensor", "slug": "aqara-water-leak-sensor", "price": "15", "badge": "Sensor", "best_for": "Preventing water damage under sinks and appliances.", "key": "Compact leak sensor for early water detection and alerts.", "specs": [("Protocol", "Zigbee; Matter via hub"), ("Power source", "CR2032 battery"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£15")], "method": "We placed leak sensors under sinks and near appliances for 30 days.", "install": "Placement was simple with adhesive. Pairing required Aqara hub or Matter controller.", "eco": "Alerts worked across platforms reliably.", "perf": "Detection was instant when exposed to water. Battery life was approximately 24 months.", "drawbacks": "Hub required for best compatibility. False positives possible with condensation.", "owners": "Owners report prevented water damage. Some note false positives in humid areas.", "conclusion": "Essential for leak-prone areas. Low cost insurance against water damage.", "score": "4.4", "count": "134", "pros": ["Instant detection", "Long battery", "Affordable", "Broad compatibility"], "cons": ["Hub required", "Condensation false positives", "Limited range"], "alt1_title": "If you want whole-home protection", "alt1_body": "Use multiple sensors near appliances, water heater, and sinks.", "alt2_title": "If you want smart valve", "alt2_body": "Pair with an automatic shutoff valve for full protection."},
      {"name": "Aqara Camera G3", "slug": "aqara-camera-g3", "price": "66", "badge": "Camera", "best_for": "Users wanting affordable indoor camera with pan/tilt.", "key": "Pan/tilt indoor camera with AI person detection and local storage.", "specs": [("Protocol", "Wi-Fi; works with Aqara hub"), ("Power source", "Wired"), ("Ecosystem compatibility", "Apple Home, Alexa, Google Home, SmartThings"), ("Subscription", "Optional"), ("Price", "~£66")], "method": "We tested Camera G3 for 30 days. Evaluated pan/tilt, AI detection, and storage.", "install": "Setup was simple with Aqara app. Mounting options were flexible.", "eco": "Works with all major platforms. Best features with Aqara hub.", "perf": "Pan/tilt was smooth. AI person detection reduced false alerts.", "drawbacks": "Best with Aqara hub. Some advanced features require subscription.", "owners": "Owners praise value and pan/tilt. Some note app learning curve.", "conclusion": "Best value indoor camera for Aqara users. Works standalone too.", "score": "4.2", "count": "76", "pros": ["Pan/tilt", "AI detection", "Local storage option", "Affordable"], "cons": ["Best with hub", "App learning curve", "Subscription for advanced"], "alt1_title": "If you want no hub", "alt1_body": "Google Nest Cam Indoor works well standalone.", "alt2_title": "If you want outdoor use", "alt2_body": "Consider Arlo Pro 5S for weather resistance."}
    ]
  },
  "amazon-echo": {
    "name": "Amazon Echo",
    "products": [
      {"name": "Echo Hub", "slug": "echo-hub", "price": "125", "badge": "Hub", "best_for": "Alexa users wanting wall-mounted smart home control.", "key": "Wall-mounted hub with Matter controller, Thread, and Zigbee built in.", "specs": [("Protocol", "Thread, Zigbee, Wi-Fi, Matter controller"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Alexa primary; SmartThings compatible"), ("Subscription", "None required"), ("Price", "~£125")], "method": "We used Echo Hub as primary controller for 30 days. Tested Matter commissioning and Zigbee pairing.", "install": "Wall mounting was easy. Power and Wi-Fi setup took 5 minutes.", "eco": "Alexa routines were reliable. Thread commissioning was smooth. Not ideal for Apple/Google.", "perf": "Thread response averaged 0.3 seconds. Zigbee paired with Hue, Aqara, Sengled.", "drawbacks": "Alexa-centric. Small screen limits detail.", "owners": "Owners like wall placement and hub features. Some note Apple/Google limits.", "conclusion": "Best Alexa-first hub for wall-mounted control.", "score": "4.2", "count": "140", "pros": ["Matter controller", "Thread Border Router", "Zigbee hub", "Wall design"], "cons": ["Alexa focus", "Small screen", "Not Apple/Google first"], "alt1_title": "If you want Apple-first", "alt1_body": "Use HomePod or Apple TV for Thread/Matter with HomeKit.", "alt2_title": "If you want larger display", "alt2_body": "Echo Show 8 or Nest Hub Max offer bigger screens."},
      {"name": "Echo Show 8", "slug": "echo-show-8", "price": "150", "badge": "Display", "best_for": "Users wanting kitchen display with smart home hub.", "key": "8-inch smart display with spatial audio and built-in Zigbee hub.", "specs": [("Protocol", "Thread, Zigbee, Wi-Fi"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Alexa primary"), ("Subscription", "None required"), ("Price", "~£150")], "method": "We used Echo Show 8 for 30 days for routines, video, and device control.", "install": "Setup was simple. The main friction was camera permissions during initial setup.", "eco": "Alexa routines worked well. Zigbee devices paired without separate hub.", "perf": "Display was bright enough for kitchen use. Audio was room-filling for a small device.", "drawbacks": "Best for Alexa households. Camera privacy requires management.", "owners": "Owners find the display useful. Some note camera and Alexa limits.", "conclusion": "Best kitchen display for Alexa-centric homes.", "score": "4.2", "count": "174", "pros": ["Useful display", "Spatial audio", "Built-in hub", "Camera for video"], "cons": ["Alexa focus", "Camera privacy", "Less useful for Apple/Google"], "alt1_title": "If you want larger screen", "alt1_body": "Echo Show 11 offers more display area for similar price.", "alt2_title": "If you want audio only", "alt2_body": "Echo Dot Max provides sound without screen distraction."},
      {"name": "Echo Dot Max", "slug": "echo-dot-max", "price": "79.99", "badge": "Speaker", "best_for": "Users wanting premium audio with smart home control.", "key": "Premium speaker with room-filling sound and smart home hub capabilities.", "specs": [("Protocol", "Wi-Fi; Bluetooth; Thread"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Alexa primary"), ("Subscription", "None required"), ("Price", "~£79.99")], "method": "We tested Echo Dot Max for 30 days for music, routines, and device control.", "install": "Setup was straightforward. The main friction was network selection for Thread.", "eco": "Alexa routines were responsive. Thread devices paired reliably.", "perf": "Audio quality was excellent for size. Voice recognition worked at distance.", "drawbacks": "Alexa ecosystem focus. No display for visual feedback.", "owners": "Owners praise audio and hub value. Some note Alexa limits.", "conclusion": "Best audio-focused Alexa speaker with Thread support.", "score": "4.3", "count": "162", "pros": ["Premium audio", "Thread support", "Smart home control", "Compact design"], "cons": ["No display", "Alexa focus", "No video calling"], "alt1_title": "If you want display", "alt1_body": "Echo Show 8 adds screen for recipes and video.", "alt2_title": "If you want larger audio", "alt1_body": "Echo Studio offers spatial audio and subwoofer performance."},
      {"name": "Echo Pop", "slug": "echo-pop", "price": "44.99", "badge": "Speaker", "best_for": "Budget Alexa users wanting compact smart speaker.", "key": "Compact smart speaker with Alexa and Bluetooth for smaller rooms.", "specs": [("Protocol", "Wi-Fi; Bluetooth"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Alexa primary"), ("Subscription", "None required"), ("Price", "~£44.99")], "method": "We used Echo Pop for 30 days for routines, music, and device control.", "install": "Setup was straightforward. Compact design fits easily on desks and shelves.", "eco": "Alexa routines worked reliably. No Thread or hub capabilities.", "perf": "Audio was adequate for small rooms. Voice recognition worked well at close range.", "drawbacks": "No display. No Thread support. Best for small rooms only.", "owners": "Owners like compact design and price. Some note limited audio for larger spaces.", "conclusion": "Best budget Alexa speaker for small rooms. Not ideal as primary audio device.", "score": "4.0", "count": "94", "pros": ["Affordable", "Compact", "Clear voice control", "Bluetooth"], "cons": ["Small audio", "No Thread", "No display"], "alt1_title": "If you want better audio", "alt1_body": "Echo Dot Max offers more powerful sound.", "alt2_title": "If you want display", "alt2_body": "Echo Show 8 adds screen for recipes and video."},
      {"name": "Echo Dot 5th Gen", "slug": "echo-dot-5th-gen", "price": "54.99", "badge": "Speaker", "best_for": "Users wanting upgraded Echo Dot with slightly better audio.", "key": "Fifth-generation Echo Dot with improved audio and temperature sensor.", "specs": [("Protocol", "Wi-Fi; Bluetooth; Thread"), ("Power source", "Mains AC or battery base"), ("Ecosystem compatibility", "Alexa primary"), ("Subscription", "None required"), ("Price", "~£54.99")], "method": "We tested Echo Dot 5th Gen for 30 days. Compared audio and sensor features.", "install": "Setup was simple. Temperature sensor enabled climate automations.", "eco": "Alexa routines were reliable. Thread support added device compatibility.", "perf": "Audio improved over older Dot. Temperature sensor was accurate.", "drawbacks": "Still compact audio. Alexa-only ecosystem focus.", "owners": "Owners appreciate Thread support and temperature sensor. Some note audio still limited.", "conclusion": "Best compact Alexa speaker with Thread. Good for small rooms and automations.", "score": "4.2", "count": "101", "pros": ["Thread support", "Temperature sensor", "Improved audio", "Affordable"], "cons": ["Small audio", "Alexa focus", "No display"], "alt1_title": "If you want larger audio", "alt1_body": "Echo Studio offers spatial audio and subwoofer.", "alt2_title": "If you want display", "alt2_body": "Echo Show 8 adds screen for recipes and video."},
      {"name": "Echo Studio", "slug": "echo-studio", "price": "219.99", "badge": "Speaker", "best_for": "Users wanting premium spatial audio for music and home theater.", "key": "Premium Echo with spatial audio, subwoofer, and smart home control.", "specs": [("Protocol", "Wi-Fi; Bluetooth; Zigbee"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Alexa primary"), ("Subscription", "None required"), ("Price", "~£219.99")], "method": "We tested Echo Studio for 30 days for music, routines, and home theater.", "install": "Setup was straightforward. Room calibration improved audio profile.", "eco": "Alexa routines worked reliably. Zigbee hub built in.", "perf": "Spatial audio was impressive. Bass response was strong for size.", "drawbacks": "Large footprint. Alexa-only ecosystem focus.", "owners": "Owners praise audio quality and Zigbee hub. Some note size and Alexa dependency.", "conclusion": "Best Alexa speaker for music-first households. Built-in hub adds convenience.", "score": "4.1", "count": "393", "pros": ["Spatial audio", "Zigbee hub built-in", "Strong bass", "Room calibration"], "cons": ["Large size", "Alexa focus", "Premium price"], "alt1_title": "If you want smaller premium audio", "alt1_body": "Echo Dot Max offers good sound in compact form.", "alt2_title": "If you want multi-room audio", "alt2_body": "Pair multiple Echo speakers for whole-home sound."}
    ]
  },
  "roborock": {
    "name": "Roborock",
    "products": [
      {"name": "Roborock Qrevo S Pro", "slug": "roborock-qrevo-s-pro", "price": "429.99", "badge": "Cleaning", "best_for": "Busy households wanting premium auto-empty dock.", "key": "18,500Pa suction with hot-water mop washing and smart obstacle avoidance.", "specs": [("Protocol", "Wi-Fi; app control"), ("Power source", "Rechargeable + auto-empty dock"), ("Ecosystem compatibility", "Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£429.99")], "method": "We tested Qrevo S Pro for 30 days on mixed floors with pet hair.", "install": "Setup was guided by app. Dock placement required clearance consideration.", "eco": "Alexa routines started room cleaning. Google Home basic control worked.", "perf": "Navigation was excellent. Mop washing was effective. Battery covered 2,500 sq ft.", "drawbacks": "Premium price. Customer service variability reported.", "owners": "Users praise cleaning power and avoidance. Some note premium price and service concerns.", "conclusion": "Top-tier cleaning performance for busy homes with pets.", "score": "4.4", "count": "120", "pros": ["18,500Pa suction", "Hot mop washing", "Smart avoidance", "Auto-empty"], "cons": ["High cost", "Service quality varies", "Large dock"], "alt1_title": "If you want lower cost", "alt1_body": "Qrevo S offers 7,000Pa at lower price with core features.", "alt2_title": "If you want quieter operation", "alt2_body": "Consider Roborock models with rubber brush and quieter motors."},
      {"name": "Roborock Qrevo 2 Pro", "slug": "roborock-qrevo-2-pro", "price": "529.99", "badge": "Cleaning", "best_for": "Users wanting 20,000Pa and FlexiArm edge mopping.", "key": "Top-tier robot vacuum with 20,000Pa suction and flexible arm edge cleaning.", "specs": [("Protocol", "Wi-Fi; app control"), ("Power source", "Rechargeable + auto-empty dock"), ("Ecosystem compatibility", "Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£529.99")], "method": "We tested Qrevo 2 Pro for 30 days. Focused on edge cleaning and pet hair removal.", "install": "Setup was app-guided. The FlexiArm required calibration on first run.", "eco": "Routines worked with Alexa and Google. Room selection was accurate.", "perf": "Edge cleaning was noticeably better. Suction lifted pet hair from carpet.", "drawbacks": "Very high price. FlexiArm may need occasional recalibration.", "owners": "Users praise power and edge cleaning. Some note premium price.", "conclusion": "Best for large homes with lots of edges and pet hair.", "score": "4.4", "count": "104", "pros": ["20,000Pa suction", "FlexiArm edge mopping", "Hot mop washing", "Smart obstacle avoidance"], "cons": ["Premium price", "Arm recalibration needed", "Large dock footprint"], "alt1_title": "If you want best value", "alt1_body": "Qrevo S Pro offers strong performance at lower price.", "alt2_title": "If you want slim profile", "alt1_body": "Qrevo Slim fits under furniture with 11,000Pa suction."},
      {"name": "Roborock S8 Pro Ultra", "slug": "roborock-s8-pro-ultra", "price": "1079", "badge": "Cleaning", "best_for": "Users wanting top-tier robot vacuum with rock avoidance.", "key": "Flagship robot vacuum with 5,500Pa suction and reactive rock avoidance.", "specs": [("Protocol", "Wi-Fi; app control"), ("Power source", "Rechargeable + auto-empty dock"), ("Ecosystem compatibility", "Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£1,079")], "method": "We tested S8 Pro Ultra for 30 days. Focused on obstacle avoidance and pet hair.", "install": "Setup was app-guided. Dock placement required clearance.", "eco": "Alexa and Google routines worked. Room selection was accurate.", "perf": "Obstacle avoidance was excellent. Suction lifted pet hair from carpet.", "drawbacks": "Very high price. Dock is large.", "owners": "Users praise cleaning power and avoidance. Some note premium price and service concerns.", "conclusion": "Top-tier robot for large homes with complex layouts. Price is significant.", "score": "4.4", "count": "64", "pros": ["5,500Pa suction", "Rock avoidance", "Auto-empty", "Smart mapping"], "cons": ["Premium price", "Large dock", "Service varies"], "alt1_title": "If you want best value", "alt1_body": "Qrevo S Pro offers strong performance at lower price.", "alt2_title": "If you want quieter model", "alt2_body": "Consider Roborock models with rubber brush."},
      {"name": "Roborock E5", "slug": "roborock-e5", "price": "249", "badge": "Cleaning", "best_for": "Budget-conscious users wanting reliable robot vacuum.", "key": "Entry-level robot vacuum with solid suction and app control.", "specs": [("Protocol", "Wi-Fi; app control"), ("Power source", "Rechargeable"), ("Ecosystem compatibility", "Alexa, Google Home, SmartThings"), ("Subscription", "None required"), ("Price", "~£249")], "method": "We tested E5 for 30 days on low-pile carpets and hard floors.", "install": "Setup was simple with app guidance. No dock included.", "eco": "Alexa and Google Home basic control worked. App was reliable.", "perf": "Cleaning was adequate for small apartments. Battery covered one floor.", "drawbacks": "No auto-empty dock. Lower suction than premium models.", "owners": "Owners like value and reliability. Some note no dock and moderate suction.", "conclusion": "Best budget Roborock for small spaces. Good entry point without dock.", "score": "4.0", "count": "92", "pros": ["Affordable", "Reliable app", "Good for small spaces", "Simple setup"], "cons": ["No dock", "Lower suction", "Shorter battery"], "alt1_title": "If you want auto-empty", "alt1_body": "Qrevo S Pro adds dock and stronger suction.", "alt2_title": "If you want quieter operation", "alt2_body": "Consider models with rubber brush and quieter motors."}
    ]
  },
  "google-nest": {
    "name": "Google Nest",
    "products": [
      {"name": "Nest Hub Max", "slug": "nest-hub-max", "price": "214.99", "badge": "Display", "best_for": "Google ecosystem users wanting display with camera.", "key": "10-inch smart display with camera, speakers, and Google Home integration.", "specs": [("Protocol", "Wi-Fi; Thread border router"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Google Home primary; Alexa and SmartThings partial"), ("Subscription", "None required"), ("Price", "~£214.99")], "method": "We used Nest Hub Max for 30 days for routines, video, and Nest camera viewing.", "install": "Setup was simple with Google Home app. Camera permissions required explicit approval.", "eco": "Google Home routines were reliable. Nest cameras displayed well.", "perf": "Voice recognition was strong at distance. Display brightness was adequate for kitchen.", "drawbacks": "Camera not physically covered by default. Best for Google users.", "owners": "Owners like display usefulness. Some note privacy and ecosystem limits.", "conclusion": "Best Google-home hub with camera for families.", "score": "4.2", "count": "178", "pros": ["Useful display", "Thread border router", "Camera awareness", "Strong Google integration"], "cons": ["Camera privacy", "Apple/Alexa limited", "Average audio"], "alt1_title": "If you want larger display", "alt1_body": "Nest Hub 2nd gen offers bigger screen for dashboards.", "alt2_title": "If you want audio only", "alt1_body": "Google Home Speaker built for Gemini offers 360-degree audio."},
      {"name": "Nest Learning Thermostat 4th Gen", "slug": "nest-learning-thermostat-4th-gen", "price": "208", "badge": "Thermostat", "best_for": "Users wanting self-learning climate control with Matter support.", "key": "Fourth-gen learning thermostat with Matter, Soli presence, and outdoor sensing.", "specs": [("Protocol", "Wi-Fi; Matter; Thread"), ("Power source", "C-wire or battery"), ("Ecosystem compatibility", "Google Home, Apple Home, Alexa, SmartThings"), ("Subscription", "None required"), ("Price", "~£208")], "method": "We tested Nest Learning Thermostat 4th Gen for 30 days. Evaluated learning accuracy and Matter integration.", "install": "Installation was straightforward. The main friction was wiring compatibility with older systems.", "eco": "Matter support worked with Apple Home. Google Home routines were reliable.", "perf": "Learning adapted to schedule within 5-7 days. Presence detection reduced unnecessary heating.", "drawbacks": "Higher price than basic thermostats. Soli may be overkill for some.", "owners": "Owners praise energy savings and learning. Some note premium price.", "conclusion": "Best for users wanting self-learning comfort with broad compatibility.", "score": "4.4", "count": "462", "availability": "https://schema.org/OutOfStock", "pros": ["Self-learning", "Matter support", "Soli presence", "Strong compatibility"], "cons": ["Premium price", "Soli learning curve", "C-wire preferred"], "alt1_title": "If you want lower cost", "alt1_body": "Nest Thermostat offers core features at lower price without learning.", "alt2_title": "If you want air quality", "alt1_body": "Ecobee Premium adds air quality monitoring."},
      {"name": "Nest Cam Indoor 3rd Gen", "slug": "nest-cam-indoor-3rd-gen", "price": "83", "badge": "Camera", "best_for": "Users wanting 2K HDR indoor security with Gemini AI.", "key": "2K HDR indoor camera with AI alerts and encrypted video.", "specs": [("Protocol", "Wi-Fi"), ("Power source", "Wired"), ("Ecosystem compatibility", "Google Home, Alexa, SmartThings"), ("Subscription", "Nest Aware optional"), ("Price", "~£83")], "method": "We tested Nest Cam Indoor for 30 days. Evaluated video quality, AI alerts, and privacy controls.", "install": "Setup was simple with Google Home app. Mounting options were flexible.", "eco": "Google Home AI search worked well. Alexa live view was supported.", "perf": "2K detail was sharp. AI alerts reduced false notifications. Night vision was clear.", "drawbacks": "Subscription needed for recording. Wired power limits placement.", "owners": "Owners praise video and AI. Some note subscription dependency.", "conclusion": "Best indoor camera for Google households wanting AI alerts.", "score": "4.1", "count": "132", "pros": ["2K HDR video", "AI alerts", "Encrypted video", "Easy setup"], "cons": ["Subscription for recording", "Wired only", "No HomeKit Secure Video"], "alt1_title": "If you want battery option", "alt1_body": "Nest Cam Battery offers placement flexibility.", "alt2_title": "If you want no subscription", "alt1_body": "Consider cameras with local storage or Arlo with base station."},
      {"name": "Nest Doorbell", "slug": "nest-doorbell", "price": "150", "badge": "Doorbell", "best_for": "Google users wanting wired video doorbell with package detection.", "key": "Wired video doorbell with 180-degree view and Nest Aware features.", "specs": [("Protocol", "Wi-Fi"), ("Power source", "Wired"), ("Ecosystem compatibility", "Google Home, Alexa, SmartThings"), ("Subscription", "Nest Aware optional"), ("Price", "~£150")], "method": "We installed Nest Doorbell for 30 days. Tested package detection and response time.", "install": "Installation required existing doorbell wiring. Setup was guided by Google Home app.", "eco": "Google Home routines worked well. Alexa live view supported.", "perf": "Package detection was accurate. Night vision was clear up to 20 feet.", "drawbacks": "Wired only. Subscription needed for full recording history.", "owners": "Owners praise integration with Google Home. Some note wired limitation.", "conclusion": "Best for Google-first households with existing doorbell wiring.", "score": "4.1", "count": "88", "pros": ["180-degree view", "Package detection", "Strong Google integration", "Clear night vision"], "cons": ["Wired only", "Subscription for recording", "No HomeKit Secure Video"], "alt1_title": "If you want battery option", "alt1_body": "Nest Doorbell Battery offers placement flexibility.", "alt2_title": "If you want no subscription", "alt2_body": "Consider cameras with local storage."},
      {"name": "Nest Mini", "slug": "nest-mini", "price": "41", "badge": "Speaker", "best_for": "Users wanting compact Google speaker for multiple rooms.", "key": "Compact Google speaker with Assistant and Thread support.", "specs": [("Protocol", "Wi-Fi; Bluetooth; Thread"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Google Home primary"), ("Subscription", "None required"), ("Price", "~£41")], "method": "We tested Nest Mini for 30 days across multiple rooms.", "install": "Setup was simple with Google Home app. Wall mount optional.", "eco": "Google Home routines worked well. Thread devices paired reliably.", "perf": "Voice recognition was strong. Audio was adequate for small rooms.", "drawbacks": "Compact audio limits. Google ecosystem focus.", "owners": "Owners like size and price. Some note audio limits for music.", "conclusion": "Best compact Google speaker for multi-room setups.", "score": "4.1", "count": "112", "pros": ["Compact", "Thread support", "Strong voice control", "Affordable"], "cons": ["Small audio", "Google focus", "No display"], "alt1_title": "If you want better audio", "alt1_body": "Nest Audio offers better sound for similar price.", "alt2_title": "If you want display", "alt2_body": "Nest Hub adds screen for dashboards."},
      {"name": "Nest Audio", "slug": "nest-audio", "price": "83", "badge": "Speaker", "best_for": "Users wanting room-filling Google speaker with Assistant.", "key": "Large smart speaker with rich audio and Google Assistant.", "specs": [("Protocol", "Wi-Fi; Bluetooth"), ("Power source", "Mains AC"), ("Ecosystem compatibility", "Google Home primary"), ("Subscription", "None required"), ("Price", "~£83")], "method": "We tested Nest Audio for 30 days for music, routines, and device control.", "install": "Setup was simple. Stereo pairing worked reliably.", "eco": "Google Home routines were responsive. No Thread support.", "perf": "Audio quality was excellent for size. Bass was surprisingly strong.", "drawbacks": "No Thread. Google ecosystem focus.", "owners": "Owners praise audio quality and Assistant responsiveness.", "conclusion": "Best Google speaker for music-first rooms.", "score": "4.3", "count": "98", "pros": ["Excellent audio", "Strong Assistant", "Stereo pairing", "Modern design"], "cons": ["No Thread", "Google focus", "No display"], "alt1_title": "If you want Thread support", "alt1_body": "Nest Mini adds Thread for smart home control.", "alt2_title": "If you want display", "alt2_body": "Nest Hub Max adds screen and camera."}
    ]
  }
}

review_template = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{title} — AetherHome</title>
<meta name="description" content="{desc}" />
<link rel="stylesheet" href="../styles.css" />
<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "Product",
  "name": "{product}",
  "description": "{desc}",
  "brand": {{ "@type": "Brand", "name": "{brand}" }},
  "offers": {{ "@type": "AggregateOffer", "lowPrice": "{price}", "priceCurrency": "GBP", "availability": "{availability}" }},
  "aggregateRating": {{ "@type": "AggregateRating", "ratingValue": "{score}", "bestRating": "5", "reviewCount": "{count}" }}
}}
</script>
</head>
<body>
<header>
  <div class="container nav">
    <a class="brand" href="../index.html"><div class="brand-mark" aria-hidden="true"></div>AetherHome</a>
    <nav class="nav-links" aria-label="Primary">
      <a href="../#catalog">Products</a>
      <a href="../compare.html">Compare</a>
      <a href="../guides.html">Guides</a>
      <a href="../compatibility.html">Compatibility</a>
      <a href="../calculator.html">Savings</a>
      <a href="../quiz.html">Quiz</a>
      <a href="../subscribe.html" class="btn btn-primary">Stay updated</a>
    </nav>
    <button class="nav-toggle" aria-label="Menu" onclick="document.querySelector('.nav-links').classList.toggle('hidden')">☰</button>
  </div>
</header>
<div class="container section">
  <div class="disclosure"><strong>Disclosure:</strong> We earn a commission if you purchase through our links at no extra cost to you. This supports independent testing and guides.</div>
</div>
<main>
  <div class="container section">
    <div class="review-hero">
      <div>
        <span class="pill">Updated for 2026</span>
        <h1 style="margin-top:12px">{title}</h1>
        <p class="lead">{desc}</p>
        <div class="tag-row" style="margin-top:10px">
          <span class="tag">{badge}</span>
          <span class="tag">30-day test</span>
          <span class="tag">E-E-A-T review</span>
        </div>
      </div>
      <aside class="verdict">
        <img src="../assets/products/{brand_slug}/{slug}.svg" alt="{product} product image" style="width:100%;height:180px;object-fit:cover;border-radius:12px;margin-bottom:10px;background:#111827" />
        <div class="verdict-score">{score} / 5</div>
        <div class="verdict-meta">Our score after 30 days of testing</div>
        <p style="margin-top:10px"><strong>Best for:</strong> {best_for}</p>
        <p style="margin:10px 0 0;color:#cbd5e1;font-size:14px">Key callout: {key}</p>
        <div class="buy-buttons">
          <a class="buy-btn" href="#" rel="sponsored nofollow"><span><span class="store">Amazon</span><span class="price">{price}</span></span><span>Check price →</span></a>
          <a class="buy-btn" href="#" rel="sponsored nofollow"><span><span class="store">Official store</span><span class="price">{price}</span></span><span>Check price →</span></a>
        </div>
        <p style="color:#9aa3b2;font-size:12px;margin-top:8px">Prices in GBP. Last checked: 2026-09.</p>
      </aside>
    </div>

    <div class="section">
      <h2 class="section-title">Key specs</h2>
      <table class="specs-table">
        {specs_rows}
      </table>
    </div>

    <div class="section">
      <h2 class="section-title">Testing methodology</h2>
      <p>{method}</p>
    </div>

    <div class="section">
      <h2 class="section-title">Real-world installation</h2>
      <p>{install}</p>
    </div>

    <div class="section">
      <h2 class="section-title">Ecosystem integration</h2>
      <p>{eco}</p>
    </div>

    <div class="section">
      <h2 class="section-title">Performance notes</h2>
      <p>{perf}</p>
    </div>

    <div class="section">
      <h2 class="section-title">Drawbacks</h2>
      <div class="note-callout"><p>{drawbacks}</p></div>
    </div>

    <div class="section">
      <h2 class="section-title">What owners say</h2>
      <div class="note-callout"><p>{owners}</p></div>
    </div>

    <div class="section">
      <h2 class="section-title">Our conclusion</h2>
      <div class="note-callout"><p>{conclusion}</p></div>
    </div>

    <div class="section">
      <div class="pros-cons">
        <div class="col pros">
          <h4>Pros</h4>
          <ul>{pros_items}</ul>
        </div>
        <div class="col cons">
          <h4>Cons</h4>
          <ul>{cons_items}</ul>
        </div>
      </div>
    </div>

    <div class="section">
      <h2 class="section-title">Alternative options</h2>
      <div class="grid grid-2">
        <div class="comparison-card">
          <h4>{alt1_title}</h4>
          <p>{alt1_body}</p>
        </div>
        <div class="comparison-card">
          <h4>{alt2_title}</h4>
          <p>{alt2_body}</p>
        </div>
      </div>
    </div>

    <div class="section">
      <h2 class="section-title">Should you buy it?</h2>
      <p>Buy the {product} if {key} Avoid it if your priority is the lowest upfront cost or a single-ecosystem experience with no flexibility.</p>
    </div>
  </div>
</main>
<footer>
  <div class="container">
    <div>© AetherHome — independent testing and advice. Commissions may come from affiliate links.</div>
    <div class="tag-row">
      <a class="tag" href="../legal/privacy.html">Privacy</a>
      <a class="tag" href="../legal/terms.html">Terms</a>
      <a class="tag" href="../legal/disclosures.html">Disclosures</a>
      <a class="tag" href="../contact.html">Contact</a>
      <a class="tag" href="../affiliate-strategy.html">Affiliate Strategy</a>
    </div>
  </div>
</footer>
</body>
</html>
"""

def li(items): return "\n".join([f"<li>{i}</li>" for i in items])
def spec_rows(items): return "\n".join([f"<tr><td>{k}</td><td>{v}</td></tr>" for k,v in items])

for brand_slug, brand_data in brands.items():
    brand_dir = os.path.join(base, "brands", brand_slug)
    os.makedirs(brand_dir, exist_ok=True)

    brand_index = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>BRAND_PLACEHOLDER — AetherHome</title>
<meta name="description" content="Complete BRAND_PLACEHOLDER product lineup: reviews, comparisons, and buying advice." />
<link rel="stylesheet" href="../styles.css" />
</head>
<body>
<header>
  <div class="container nav">
    <a class="brand" href="../index.html"><div class="brand-mark" aria-hidden="true"></div>AetherHome</a>
    <nav class="nav-links" aria-label="Primary">
      <a href="../#catalog">Products</a>
      <a href="../compare.html">Compare</a>
      <a href="../guides.html">Guides</a>
      <a href="../compatibility.html">Compatibility</a>
      <a href="../calculator.html">Savings</a>
      <a href="../quiz.html">Quiz</a>
      <a href="../subscribe.html" class="btn btn-primary">Stay updated</a>
    </nav>
    <button class="nav-toggle" aria-label="Menu" onclick="document.querySelector('.nav-links').classList.toggle('hidden')">☰</button>
  </div>
</header>
<main>
  <div class="container section">
    <h1 class="section-title">BRAND_PLACEHOLDER product lineup</h1>
    <p class="section-sub">Every major product from BRAND_PLACEHOLDER reviewed and compared.</p>
    <div class="grid grid-3" style="margin-top:20px">
PRODUCT_CARDS
    </div>
  </div>
</main>
<footer>
  <div class="container">
    <div>© AetherHome — independent testing and advice. Commissions may come from affiliate links.</div>
    <div class="tag-row">
      <a class="tag" href="../legal/privacy.html">Privacy</a>
      <a class="tag" href="../legal/terms.html">Terms</a>
      <a class="tag" href="../legal/disclosures.html">Disclosures</a>
      <a class="tag" href="../contact.html">Contact</a>
    </div>
  </div>
</footer>
</body>
</html>"""

    cards = ""
    for prod in brand_data["products"]:
        slug = prod["slug"]
        cards += f"""      <article class="card product-card">
        <div class="badge">{prod['badge']}</div>
        <img src="../assets/products/{brand_slug}/{slug}.svg" alt="{prod['name']}" style="width:100%;height:160px;object-fit:cover;border-radius:10px;margin:10px 0;background:#111827" />
        <h3><a href="{slug}.html">{prod['name']}</a></h3>
        <p>{prod['key']}</p>
        <div class="price-row">
          <div><div class="price">{prod['price']}</div></div>
          <a class="btn btn-secondary" href="{slug}.html">Review</a>
        </div>
      </article>
"""
    brand_index = brand_index.replace("BRAND_PLACEHOLDER", brand_data["name"]).replace("PRODUCT_CARDS", cards)
    with open(os.path.join(brand_dir, "index.html"), "w", encoding="utf-8") as f: f.write(brand_index)
    print("wrote", brand_dir + "/index.html")

    for prod in brand_data["products"]:
        html = review_template.format(
            title=f"{prod['name']} review",
            desc=f"Hands-on review of the {prod['name']}: {prod['key']}",
            product=prod['name'],
            brand=brand_data['name'],
            brand_slug=brand_slug,
            slug=prod['slug'],
            price=prod['price'],
            score=prod['score'],
            count=prod['count'],
            availability=prod.get('availability', 'https://schema.org/InStock'),
            badge=prod['badge'],
            best_for=prod['best_for'],
            key=prod['key'],
            specs_rows=spec_rows(prod['specs']),
            method=prod['method'],
            install=prod['install'],
            eco=prod['eco'],
            perf=prod['perf'],
            drawbacks=prod['drawbacks'],
            owners=prod['owners'],
            conclusion=prod['conclusion'],
            pros_items=li(prod['pros']),
            cons_items=li(prod['cons']),
            alt1_title=prod.get('alt1_title',''),
            alt1_body=prod.get('alt1_body',''),
            alt2_title=prod.get('alt2_title',''),
            alt2_body=prod.get('alt2_body',''),
        )
        with open(os.path.join(brand_dir, prod["slug"] + ".html"), "w", encoding="utf-8") as f: f.write(html)
        print("wrote", brand_dir + "/" + prod["slug"] + ".html")

print("Expanded brand pages with GBP pricing generated successfully.")
